Refactor handling reward tokens
Sktls-Crypto/sktl-token-wallet pull request #1
Opened 2021-12-16 18:22 UTC by wohlrich

Track total number of tokens minted to use with calculating per token rewards.
Remove rewardTokenBalance and hard-coded totalRewardToken.

The contract tracks the amount of rewards per token claimed per account.
Accounts automatically claim any unclaimed reward tokens before any transfers 
into or out of the account occurs, so the balances should be up-to-date during any transaction.

2021-12-22 03:48 UTC, ChromeHearts requested changes

2021-12-22 03:48 UTC, ChromeHearts commented on contracts/sktl20.sol
> +    uint256 public totalTokens = 0;
No need to keep track of totalToken.  Use totalSupply()

2021-12-22 03:48 UTC, ChromeHearts commented on contracts/sktl20.sol
> +        // TODO - Does balanceOf return tokens or wei?  What aboouot reward_balance?
Remove comments, everything should be in Wei

2021-12-22 03:50 UTC, ChromeHearts commented
@wohlrich please also rebase to the latest master.  Especially, the _beforeTokenTransfer, the latest version is very different from the changes you have made.

2021-12-25 02:49 UTC, closed without merging

2021-12-25 02:50 UTC, wohlrich commented
closing PR to deprecated file.